
#ifndef TMR1_CONFIG_H_
#define TMR1_CONFIG_H_


#define TMR1_PRELOAD_VALUE			60752
#define TMR1_OVERFLOW_COUNTER	 	20

#define TMR1_COMPARE_VALUE_A 5
#define TMR1_CTC_COUNTER_A   5


#endif /* TMR1_CONFIG_H_ */
